name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master   # Triggers this workflow on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python and install dependencies
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Install the dependencies and target them into the package directory
          pip install --target ./package PyNaCl
          
          # Create a package by copying all files and zipping it
          zip -r9 lambda_function.zip ./package
          zip -g lambda_function.zip lambda_function.py

      # Step 3: Configure AWS credentials (make sure to have secrets set up in GitHub)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Deploy the packaged Lambda function
      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name StudioDiscordBot \
            --zip-file fileb://lambda_function.zip
